package handlers

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/wirewarp/agent/internal/config"
	"gopkg.in/yaml.v3"
)

const (
	edgeBackoffBase       = 60 * time.Second
	edgeBackoffMax        = 30 * time.Minute
	appSecAcquisitionFile = "/etc/crowdsec/acquis.d/wirewarp-appsec.yaml"
	appSecConfigDir       = "/etc/crowdsec/appsec-configs"
	appSecObserveName     = "wirewarp/observe"
	appSecBlockName       = "wirewarp/block"
)

type EdgeDesiredStateParams struct {
	Whitelist            CrowdSecInstallParams `json:"whitelist"`
	TraefikStaticConfig  map[string]any        `json:"traefik_static_config"`
	TraefikDynamicConfig map[string]any        `json:"traefik_dynamic_config"`
}

func (h *ServerHandlers) handleEdgeDesiredState(raw json.RawMessage) (string, error) {
	var p EdgeDesiredStateParams
	if err := json.Unmarshal(raw, &p); err != nil {
		return "", fmt.Errorf("parse params: %w", err)
	}
	h.cfg.EdgeDesired = &config.EdgeDesiredState{
		Whitelist: config.EdgeWhitelist{
			IPs:   append([]string(nil), p.Whitelist.IPs...),
			CIDRs: append([]string(nil), p.Whitelist.CIDRs...),
		},
		TraefikStaticConfig:  p.TraefikStaticConfig,
		TraefikDynamicConfig: p.TraefikDynamicConfig,
	}
	if h.cfg.EdgeBouncerKey == "" {
		key, err := generateBouncerKey()
		if err != nil {
			return "", err
		}
		h.cfg.EdgeBouncerKey = key
	}
	if err := h.cfg.Save(h.cfgPath); err != nil {
		return "", fmt.Errorf("persist desired edge state: %w", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	if err := h.reconcileDesiredEdge(ctx); err != nil {
		return "desired edge state saved; reconcile degraded", err
	}
	return "desired edge state saved and reconciled", nil
}

func generateBouncerKey() (string, error) {
	var b [32]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("generate bouncer key: %w", err)
	}
	return hex.EncodeToString(b[:]), nil
}

func edgeBackoffDuration(attempt int) time.Duration {
	if attempt <= 0 {
		return edgeBackoffBase
	}
	d := edgeBackoffBase << attempt
	if d > edgeBackoffMax {
		return edgeBackoffMax
	}
	return d
}

func injectBouncerKey(in map[string]any, key string) map[string]any {
	if in == nil {
		return nil
	}
	data, err := json.Marshal(in)
	if err != nil {
		return in
	}
	var out map[string]any
	if err := json.Unmarshal(data, &out); err != nil {
		return in
	}
	http, _ := out["http"].(map[string]any)
	middlewares, _ := http["middlewares"].(map[string]any)
	for _, mwRaw := range middlewares {
		mw, _ := mwRaw.(map[string]any)
		plugin, _ := mw["plugin"].(map[string]any)
		bouncer, _ := plugin["bouncer"].(map[string]any)
		if bouncer == nil {
			continue
		}
		if _, ok := bouncer["crowdsecLapiKey"]; ok {
			bouncer["crowdsecLapiKey"] = key
		}
	}
	return out
}

func buildAppSecAcquisition(block bool) map[string]any {
	mode := "observe"
	modeConfig := appSecObserveName
	if block {
		mode = "block"
		modeConfig = appSecBlockName
	}
	return map[string]any{
		"source":      "appsec",
		"listen_addr": "127.0.0.1:7422",
		"path":        "/",
		"appsec_configs": []string{
			"crowdsecurity/appsec-default",
			"crowdsecurity/crs",
			modeConfig,
		},
		"labels": map[string]string{
			"type":          "appsec",
			"wirewarp_mode": mode,
		},
	}
}

func buildAppSecModeConfig(block bool) map[string]any {
	name := appSecObserveName
	remediation := "allow"
	mode := "observe"
	if block {
		name = appSecBlockName
		remediation = "ban"
		mode = "block"
	}
	return map[string]any{
		"name":                name,
		"default_remediation": remediation,
		"default_pass_action": "allow",
		"labels": map[string]string{
			"wirewarp_mode": mode,
		},
	}
}

func writeAppSecModeConfigs() error {
	if err := os.MkdirAll(appSecConfigDir, 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", appSecConfigDir, err)
	}
	for _, mode := range []struct {
		block bool
		file  string
	}{
		{block: false, file: filepath.Join(appSecConfigDir, "wirewarp-observe.yaml")},
		{block: true, file: filepath.Join(appSecConfigDir, "wirewarp-block.yaml")},
	} {
		data, err := yaml.Marshal(buildAppSecModeConfig(mode.block))
		if err != nil {
			return fmt.Errorf("marshal appsec mode config: %w", err)
		}
		header := "# AUTO-GENERATED by wirewarp-agent; do not edit by hand.\n"
		if err := os.WriteFile(mode.file, append([]byte(header), data...), 0644); err != nil {
			return fmt.Errorf("write %s: %w", mode.file, err)
		}
	}
	return nil
}

func writeAppSecAcquisition(block bool) (bool, error) {
	if err := writeAppSecModeConfigs(); err != nil {
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(appSecAcquisitionFile), 0755); err != nil {
		return false, fmt.Errorf("mkdir %s: %w", filepath.Dir(appSecAcquisitionFile), err)
	}
	data, err := yaml.Marshal(buildAppSecAcquisition(block))
	if err != nil {
		return false, fmt.Errorf("marshal appsec acquisition: %w", err)
	}
	header := "# AUTO-GENERATED by wirewarp-agent; do not edit by hand.\n"
	next := append([]byte(header), data...)
	if current, err := os.ReadFile(appSecAcquisitionFile); err == nil && string(current) == string(next) {
		return false, nil
	}
	return true, os.WriteFile(appSecAcquisitionFile, next, 0644)
}

func desiredUsesWAF(dynamic map[string]any) (uses bool, block bool) {
	uses = true
	http, _ := dynamic["http"].(map[string]any)
	middlewares, _ := http["middlewares"].(map[string]any)
	for _, mwRaw := range middlewares {
		mw, _ := mwRaw.(map[string]any)
		plugin, _ := mw["plugin"].(map[string]any)
		bouncer, _ := plugin["bouncer"].(map[string]any)
		if bouncer == nil {
			continue
		}
		if failureBlock, _ := bouncer["crowdsecAppsecFailureBlock"].(bool); failureBlock {
			block = true
		}
	}
	return uses, block
}

func (h *ServerHandlers) desiredWhitelist() CrowdSecInstallParams {
	if h.cfg.EdgeDesired == nil {
		return CrowdSecInstallParams{}
	}
	return CrowdSecInstallParams{
		IPs:   append([]string(nil), h.cfg.EdgeDesired.Whitelist.IPs...),
		CIDRs: append([]string(nil), h.cfg.EdgeDesired.Whitelist.CIDRs...),
	}
}

func (h *ServerHandlers) reconcileDesiredEdge(ctx context.Context) error {
	if h.cfg.EdgeDesired == nil {
		return nil
	}

	var firstErr error
	whitelist := h.desiredWhitelist()
	if resolveCSCli() == "" {
		raw, _ := json.Marshal(whitelist)
		if _, err := h.handleCrowdSecInstall(raw); err != nil && firstErr == nil {
			firstErr = err
		}
	} else {
		raw, _ := json.Marshal(whitelist)
		if _, err := h.handleCrowdSecSyncWhitelist(raw); err != nil && firstErr == nil {
			firstErr = err
		}
	}

	usesWAF, block := desiredUsesWAF(h.cfg.EdgeDesired.TraefikDynamicConfig)
	if usesWAF {
		appsecChanged, err := writeAppSecAcquisition(block)
		if err != nil && firstErr == nil {
			firstErr = err
		}
		if h.cfg.EdgeBouncerKey == "" {
			key, err := generateBouncerKey()
			if err != nil && firstErr == nil {
				firstErr = err
			} else {
				h.cfg.EdgeBouncerKey = key
				_ = h.cfg.Save(h.cfgPath)
			}
		}
		needsBootstrap := appsecChanged
		if bin := resolveCSCli(); bin != "" && !crowdSecBouncerRegistered(ctx, bin) {
			needsBootstrap = true
		}
		if needsBootstrap {
			appsecRaw, _ := json.Marshal(CrowdSecAppSecParams{BouncerKey: h.cfg.EdgeBouncerKey})
			if _, err := h.handleCrowdSecAppSecEnable(appsecRaw); err != nil && firstErr == nil {
				firstErr = err
			}
		}
	}

	if h.cfg.EdgeDesired.TraefikStaticConfig != nil {
		raw, _ := json.Marshal(TraefikInstallParams{StaticConfig: h.cfg.EdgeDesired.TraefikStaticConfig})
		if _, err := h.handleTraefikInstall(raw); err != nil && firstErr == nil {
			firstErr = err
		}
	}
	if h.cfg.EdgeDesired.TraefikDynamicConfig != nil {
		dynamic := injectBouncerKey(h.cfg.EdgeDesired.TraefikDynamicConfig, h.cfg.EdgeBouncerKey)
		raw, _ := json.Marshal(TraefikSyncConfigParams{DynamicConfig: dynamic})
		if _, err := h.handleTraefikSyncConfig(raw); err != nil && firstErr == nil {
			firstErr = err
		}
	}
	h.pollAndEmitCrowdSec(ctx, false)
	h.pollAndEmitTraefik(ctx, false)
	return firstErr
}
