"""Traefik install + dynamic-config rendering.

The server owns the Traefik config schema; the agent is a dumb writer
that takes the rendered dict and writes it verbatim as YAML to
/etc/traefik/dynamic/wirewarp.yml, then reloads Traefik. This mirrors
how writeWhitelist works for CrowdSec.

Key functions:
  build_traefik_static_config  - static config dict for traefik_install
  build_traefik_dynamic_config - dynamic config dict for traefik_sync_config
  dispatch_traefik_sync        - build + send traefik_sync_config to an agent
"""
from __future__ import annotations

import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.edge_route_config import EdgeRouteConfig
from app.models.port_forward import PortForward
from app.models.system_settings import SystemSettings
from app.models.tunnel_server import TunnelServer
from app.services.secrets import get_captcha_secret_key


def build_traefik_static_config(
    le_email: str | None = None,
    version: str | None = None,
) -> dict:
    """Build the Traefik static configuration dict.

    The agent writes this verbatim as /etc/traefik/traefik.yml. The
    file-provider watches /etc/traefik/dynamic/ so the server can push
    dynamic config separately without a full Traefik restart.

    `le_email` enables Let's Encrypt ACME TLS (recommended for
    production). When None, TLS termination falls back to a self-signed
    cert generated by Traefik.
    """
    cfg: dict = {
        "global": {"checkNewVersion": False, "sendAnonymousUsage": False},
        "log": {"level": "INFO"},
        "accessLog": {},
        "api": {"dashboard": False},
        "entryPoints": {
            "web": {
                "address": ":80",
                "http": {
                    "redirections": {
                        "entryPoint": {"to": "websecure", "scheme": "https"}
                    }
                },
            },
            "websecure": {"address": ":443"},
        },
        "providers": {
            "file": {
                "directory": "/etc/traefik/dynamic",
                "watch": True,
            }
        },
        # CrowdSec bouncer plugin — loaded here so it's available for every
        # dynamic config that references it. The plugin itself is installed
        # by the agent via 'traefik install --plugin'.
        "experimental": {
            "plugins": {
                "bouncer": {
                    "moduleName": "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin",
                    "version": "v1.4.5",
                },
                "denyip": {
                    "moduleName": "github.com/kvncrw/denyip",
                    "version": "v1.3.0",
                },
                "geoblock": {
                    "moduleName": "github.com/nscuro/traefik-plugin-geoblock",
                    "version": "v0.14.0",
                },
            }
        },
    }

    if le_email:
        cfg["certificatesResolvers"] = {
            "wirewarp-le": {
                "acme": {
                    "email": le_email,
                    "storage": "/etc/traefik/acme.json",
                    "tlsChallenge": {},
                }
            }
        }

    return cfg


async def build_traefik_dynamic_config(
    server_agent_id: uuid.UUID | str,
    db: AsyncSession,
) -> dict:
    """Build Traefik dynamic config for all HTTP sites on the given server agent.

    Renders routers, services, and middleware chains from the
    port_forwards + edge_route_configs tables. The agent writes the
    returned dict verbatim as YAML.

    Raw (service_kind='raw') forwards are excluded — they stay iptables DNAT.
    """
    agent_id_str = str(server_agent_id)

    server = await db.scalar(
        select(TunnelServer).where(TunnelServer.agent_id == server_agent_id)
    )

    # Load all HTTP port_forwards for this server agent. We join through
    # TunnelServer to scope by agent_id, then through attachments.
    from app.models.tunnel_client_attachment import TunnelClientAttachment

    if server is None:
        return {"http": {"routers": {}, "services": {}, "middlewares": {}}}

    # Find all attachment IDs for this server
    att_ids_result = await db.execute(
        select(TunnelClientAttachment.id).where(
            TunnelClientAttachment.tunnel_server_id == server.id
        )
    )
    att_ids = [row[0] for row in att_ids_result.all()]

    http_forwards: list[PortForward] = []
    if att_ids:
        pf_result = await db.execute(
            select(PortForward).where(
                PortForward.attachment_id.in_(att_ids),
                PortForward.service_kind == "http",
                PortForward.active == True,  # noqa: E712
            )
        )
        http_forwards = list(pf_result.scalars().all())

    # Check global middleware needs up front.
    has_waf = False
    has_waf_block = False
    has_antibot = False
    edge_configs: dict[str, EdgeRouteConfig] = {}
    for pf in http_forwards:
        ec = await db.scalar(
            select(EdgeRouteConfig).where(EdgeRouteConfig.port_forward_id == pf.id)
        )
        if ec is not None:
            edge_configs[str(pf.id)] = ec
            if ec.waf_mode != "off":
                has_waf = True
            if ec.waf_mode == "block":
                has_waf_block = True
            if ec.antibot:
                has_antibot = True

    routers: dict = {}
    services: dict = {}
    middlewares: dict = {}

    captcha: dict = {}
    if has_antibot:
        settings = await db.get(SystemSettings, 1)
        secret = await get_captcha_secret_key(db)
        if settings and settings.captcha_provider and settings.captcha_site_key and secret:
            captcha = {
                "captchaProvider": settings.captcha_provider,
                "captchaSiteKey": settings.captcha_site_key,
                "captchaSecretKey": secret,
                "captchaGracePeriodSeconds": 1800,
                "captchaHTMLFilePath": "/etc/traefik/captcha.html",
            }

    # The agent injects the local bouncer key before writing this file.
    if has_waf or has_antibot:
        bouncer_cfg = {
            "enabled": True,
            "crowdsecMode": "stream",
            "crowdsecLapiScheme": "http",
            "crowdsecLapiHost": "localhost:8080",
            "crowdsecLapiKey": "${WIREWARP_CROWDSEC_BOUNCER_KEY}",
            "httpTimeoutSeconds": 60,
            "crowdsecAppsecEnabled": has_waf,
            "crowdsecAppsecHost": "127.0.0.1:7422",
            "crowdsecAppsecFailureBlock": has_waf_block,
            "crowdsecAppsecUnreachableBlock": False,
        }
        bouncer_cfg.update(captcha)
        middlewares["crowdsec-bouncer"] = {
            "plugin": {
                "bouncer": bouncer_cfg,
            }
        }

    for pf in http_forwards:
        pf_id = str(pf.id)
        # Sanitise: replace dots/colons in domain for Traefik router name
        safe_name = (pf.domain or pf_id).replace(".", "-").replace(":", "-")
        ec = edge_configs.get(pf_id)

        router_middlewares: list[str] = []

        # Rate limiting middleware
        if ec and ec.rate_limit_rps:
            mw_name = f"ratelimit-{safe_name}"
            burst = ec.rate_limit_burst or ec.rate_limit_rps * 5
            middlewares[mw_name] = {
                "rateLimit": {
                    "average": ec.rate_limit_rps,
                    "burst": burst,
                }
            }
            router_middlewares.append(mw_name)

        # IP allowlist middleware
        if ec and ec.ip_allow:
            mw_name = f"ipallow-{safe_name}"
            middlewares[mw_name] = {
                "ipAllowList": {"sourceRange": ec.ip_allow}
            }
            router_middlewares.append(mw_name)

        if ec and ec.ip_deny:
            mw_name = f"ipdeny-{safe_name}"
            middlewares[mw_name] = {
                "plugin": {"ipDenyList": ec.ip_deny}
            }
            router_middlewares.append(mw_name)

        if ec and ec.geo_block:
            mw_name = f"geoblock-{safe_name}"
            middlewares[mw_name] = {
                "plugin": {
                    "geoblock": {
                        "enabled": True,
                        "blockedCountries": ec.geo_block,
                        "defaultAllow": True,
                        "allowPrivate": True,
                        "disallowedStatusCode": 403,
                    }
                }
            }
            router_middlewares.append(mw_name)

        # WAF / CrowdSec bouncer
        if ec and (ec.waf_mode != "off" or ec.antibot):
            router_middlewares.append("crowdsec-bouncer")

        # Basic auth
        if ec and ec.auth_mode == "basic" and ec.auth_config:
            mw_name = f"basicauth-{safe_name}"
            middlewares[mw_name] = {"basicAuth": ec.auth_config}
            router_middlewares.append(mw_name)

        # Forward auth
        if ec and ec.auth_mode == "forward" and ec.auth_config:
            mw_name = f"forwardauth-{safe_name}"
            middlewares[mw_name] = {"forwardAuth": ec.auth_config}
            router_middlewares.append(mw_name)

        # Router rule: Host header match or catch-all
        if pf.domain:
            rule = f"Host(`{pf.domain}`)"
        else:
            rule = f"PathPrefix(`/`)"

        # TLS config
        tls_source = ec.tls_source if ec else "letsencrypt"
        tls_cfg: dict = {}
        if tls_source == "letsencrypt":
            tls_cfg = {"certResolver": "wirewarp-le"}
        else:
            tls_cfg = {}

        routers[safe_name] = {
            "rule": rule,
            "service": f"svc-{safe_name}",
            "entryPoints": ["websecure"],
            "tls": tls_cfg,
            **({"middlewares": router_middlewares} if router_middlewares else {}),
        }

        services[f"svc-{safe_name}"] = {
            "loadBalancer": {
                "servers": [
                    {"url": f"http://{pf.destination_ip}:{pf.destination_port}"}
                ]
            }
        }

    return {
        "http": {
            "routers": routers,
            "services": services,
            "middlewares": middlewares,
        }
    }


async def dispatch_traefik_sync(
    agent_id: str,
    db: AsyncSession,
    actor_user_id: uuid.UUID | None = None,
) -> tuple[bool, str]:
    """Build and dispatch traefik_sync_config to the given agent.

    Returns (sent, command_id). Not sent when agent is offline — the
    agent's heal loop re-asserts from disk on reconnect.
    """
    from app.services.agent_commands import send_command

    dynamic = await build_traefik_dynamic_config(agent_id, db)
    return await send_command(
        agent_id=agent_id,
        command_type="traefik_sync_config",
        params={"dynamic_config": dynamic},
        db=db,
        actor_user_id=actor_user_id,
    )
